spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foxmonshop?serverTimezone=Asia/Seoul
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ## AUTO DROP-TABLE & CREATE => 변경사항만...
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect

## Log level
logging:
  level:
    ## Hibernate Log
    org.hibernate.SQL: debug
    ## Parameters
    org.hibernate.type: trace

